name: mia_prima_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.0
  path: ^1.8.0
  webview_flutter: ^2.0.2
  passwordfield: ^0.0.82
  path_provider: ^2.0.1
  syncfusion_flutter_calendar: ^19.4.38
  syncfusion_localizations: ^19.2.57
  flutter_form_builder: ^6.0.1
  #dropdownfield: ^1.0.3
  loading: ^1.0.2
  firebase_messaging: ^10.0.6
  rflutter_alert: ^1.0.2
  file_picker: ^4.0.0
  fluttertoast: ^5.0.0
  flutter_notification_channel: ^1.0.2
  flutter_local_notifications: ^9.1.5
  stack: ^0.0.1
  timelines: ^0.1.0
  multipart_request: ^0.3.1
  cached_network_image: ^3.0.0
  flutter_cache_manager: ^3.1.2
  images_picker: ^1.2.4
  video_thumbnail: ^0.4.3
  better_player:
    git:
      url: git@github.com:maub69/better-player.git
  open_file: ^3.2.1
  ext_storage: ^1.0.3
  permission_handler: ^8.3.0
  firebase_core: ^1.6.0
  alert: ^2.0.1
  uuid: ^3.0.4
  connectivity_plus: ^1.1.0
  pop_bottom_menu: ^1.0.0
  url_launcher: ^6.0.12
  flutter_inappwebview: ^5.3.2



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/play-button.png # https://www.flaticon.com/free-icon/play-button_189638?term=play&page=1&position=74&page=1&position=74&related_id=189638&origin=search
    - images/file.png # https://www.flaticon.com/free-icon/document_2258843?term=file&page=1&position=13&page=1&position=13&related_id=2258843&origin=search
    - images/download.png # https://www.flaticon.com/premium-icon/download-arrow_62055?term=download&page=1&position=1&page=1&position=1&related_id=62055&origin=search
    #   - images/a_dot_ham.jpeg
    - files/cliente.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
